#!/bin/bash
# Quick Supabase Setup - Gematria Hive
# Automates everything possible once you have credentials

set -e

echo "============================================================"
echo "GEMATRIA HIVE - QUICK SUPABASE SETUP"
echo "============================================================"
echo ""

# Check if credentials provided as arguments
if [ "$#" -eq 2 ]; then
    SUPABASE_URL="$1"
    SUPABASE_KEY="$2"
    echo "✅ Using provided credentials"
    echo ""
    
    # Create .env file
    cat > .env << EOF
# Gematria Hive - Environment Variables
# Generated by quick_setup_supabase.sh

SUPABASE_URL=$SUPABASE_URL
SUPABASE_KEY=$SUPABASE_KEY
EOF
    
    echo "✅ Created .env file"
    echo ""
else
    echo "⚠️  No credentials provided"
    echo ""
    echo "Usage:"
    echo "  ./quick_setup_supabase.sh <SUPABASE_URL> <SUPABASE_KEY>"
    echo ""
    echo "Or set environment variables manually:"
    echo "  1. Create .env file with SUPABASE_URL and SUPABASE_KEY"
    echo "  2. Run: python setup_database.py"
    echo ""
    echo "To get credentials:"
    echo "  1. Go to https://supabase.com"
    echo "  2. Create project: gematria-hive"
    echo "  3. Go to Settings → API"
    echo "  4. Copy Project URL → SUPABASE_URL"
    echo "  5. Copy anon public key → SUPABASE_KEY"
    echo ""
    exit 1
fi

# Activate conda environment
echo "🐍 Activating conda environment..."
source "$(conda info --base)/etc/profile.d/conda.sh" 2>/dev/null || true)"
conda activate gematria_env || {
    echo "⚠️  Conda activation failed, trying without..."
}

# Test connection
echo ""
echo "🔌 Testing connection..."
python setup_database.py --verify-only

echo ""
echo "============================================================"
echo "SETUP COMPLETE!"
echo "============================================================"
echo ""
echo "Next steps:"
echo "1. Enable pgvector in Supabase SQL Editor:"
echo "   CREATE EXTENSION IF NOT EXISTS vector;"
echo ""
echo "2. Run migrations in Supabase SQL Editor:"
echo "   - migrations/create_gematria_tables.sql"
echo "   - migrations/create_complete_schema.sql"
echo ""
echo "3. Verify setup:"
echo "   python setup_database.py"
echo ""

