#!/usr/bin/env python3
"""
Quick Supabase Setup - Gematria Hive
Automates everything possible once you have credentials

Usage:
    python quick_setup.py <SUPABASE_URL> <SUPABASE_KEY>
    python quick_setup.py  # Interactive mode
"""

import sys
import os
from pathlib import Path

def main():
    """Quick setup with credentials"""
    print("=" * 70)
    print("GEMATRIA HIVE - QUICK SUPABASE SETUP")
    print("=" * 70)
    print()
    
    # Get credentials
    if len(sys.argv) == 3:
        supabase_url = sys.argv[1]
        supabase_key = sys.argv[2]
        print(f"✅ Using provided credentials")
        print(f"   URL: {supabase_url[:40]}...")
        print(f"   Key: {supabase_key[:20]}...")
        print()
    else:
        print("⚠️  No credentials provided")
        print()
        print("Usage:")
        print("  python quick_setup.py <SUPABASE_URL> <SUPABASE_KEY>")
        print()
        print("Or run interactively:")
        print("  python quick_setup.py")
        print()
        
        # Try interactive mode
        try:
            supabase_url = input("Enter SUPABASE_URL: ").strip()
            supabase_key = input("Enter SUPABASE_KEY: ").strip()
            
            if not supabase_url or not supabase_key:
                print("❌ Credentials required")
                sys.exit(1)
        except (EOFError, KeyboardInterrupt):
            print("\n❌ Setup cancelled")
            sys.exit(1)
    
    # Create .env file
    env_file = Path(".env")
    env_content = f"""# Gematria Hive - Environment Variables
# Generated by quick_setup.py

SUPABASE_URL={supabase_url}
SUPABASE_KEY={supabase_key}
"""
    
    with open(env_file, 'w') as f:
        f.write(env_content)
    
    print(f"✅ Created .env file")
    print()
    
    # Test connection
    print("🔌 Testing connection...")
    print()
    
    os.environ['SUPABASE_URL'] = supabase_url
    os.environ['SUPABASE_KEY'] = supabase_key
    
    try:
        from supabase import create_client
        supabase = create_client(supabase_url, supabase_key)
        
        # Test connection
        result = supabase.table('bookmarks').select('*').limit(1).execute()
        print("✅ Connection successful!")
        print()
        
        # Check if tables exist
        print("📊 Checking tables...")
        required_tables = ['bookmarks', 'gematria_words', 'authors', 'sources']
        existing = []
        missing = []
        
        for table in required_tables:
            try:
                supabase.table(table).select('*').limit(1).execute()
                existing.append(table)
                print(f"   ✅ {table}")
            except:
                missing.append(table)
                print(f"   ❌ {table} - not found")
        
        print()
        
        if missing:
            print("⚠️  Some tables are missing")
            print()
            print("Next steps:")
            print("1. Enable pgvector in Supabase SQL Editor:")
            print("   CREATE EXTENSION IF NOT EXISTS vector;")
            print()
            print("2. Run migrations in Supabase SQL Editor:")
            print("   - migrations/create_gematria_tables.sql")
            print("   - migrations/create_complete_schema.sql")
            print()
            print("3. Verify setup:")
            print("   python setup_database.py")
        else:
            print("✅ All tables exist!")
            print()
            print("Setup complete! 🎉")
        
    except Exception as e:
        print(f"❌ Connection failed: {e}")
        print()
        print("This might be expected if:")
        print("  - Tables don't exist yet (run migrations)")
        print("  - Project is paused (free tier)")
        print("  - Credentials are incorrect")
        print()
        print("Next steps:")
        print("1. Verify credentials in Supabase Dashboard")
        print("2. Enable pgvector: CREATE EXTENSION IF NOT EXISTS vector;")
        print("3. Run migrations in Supabase SQL Editor")
        print("4. Test again: python setup_database.py")
        sys.exit(1)

if __name__ == "__main__":
    main()

